# Generated by Django 5.2.1 on 2025-07-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delete_status_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(3, 'ORDER PROCESSED'), (4, 'ORDER DELIVERED'), (5, 'ORDER CANCELLED')], default=1),
        ),
    ]
